version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust heap size if needed
      - "logger.level=debug" # Set the log level to debug
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped # Restart unless explicitly stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./custom_log4j2.properties:/usr/share/logstash/config/log4j2.properties # Mount custom log4j2.properties file
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    restart: unless-stopped # Restart unless explicitly stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped # Restart unless explicitly stopped

volumes:
  elasticsearch-data:
    driver: local